#!/usr/bin/env bash

while read -r line
do
    line="${line//$'\t'/$'\n'}"
    line="${line//(T)/(Technical)}"
    line="${line//(F)/(Finance)}"
    line="${line//(C)/(Consultancy)}"
    echo "$line" >> modrawText.txt
done < rawText.txt

